name: Calendar Sync

on:
  repository_dispatch:
    types: [calendar-sync]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Create config files
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          CALENDAR_CONFIG: ${{ secrets.CALENDAR_CONFIG }}
          MY_SCHEDULE: ${{ secrets.MY_SCHEDULE }}
        run: |
          # Create service account file
          echo "$SERVICE_ACCOUNT_KEY" > service-account-key.json
          
          # ALSO create it as credentials.json for compatibility
          echo "$SERVICE_ACCOUNT_KEY" > credentials.json
          
          # Create a dummy token.pickle to skip OAuth
          python -c "import pickle; pickle.dump(None, open('token.pickle', 'wb'))"
          
          # Create other files
          echo "$CALENDAR_CONFIG" > calendar_config.json
          echo "$MY_SCHEDULE" > my_schedule.py
          
          # Debug
          echo "Files created:"
          ls -la *.json *.py *.pickle
      
      - name: Run calendar update
        run: |
          python push_schedule.py --dry-run