name: Calendar Sync

on:
  repository_dispatch:
    types: [calendar-sync]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Debug secrets
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          CALENDAR_CONFIG: ${{ secrets.CALENDAR_CONFIG }}
          MY_SCHEDULE: ${{ secrets.MY_SCHEDULE }}
        run: |
          # Check if secrets exist
          echo "GOOGLE_CREDENTIALS length: ${#GOOGLE_CREDENTIALS}"
          echo "CALENDAR_CONFIG length: ${#CALENDAR_CONFIG}"
          echo "MY_SCHEDULE length: ${#MY_SCHEDULE}"
          
          # Create files
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          echo "$CALENDAR_CONFIG" > calendar_config.json
          echo "$MY_SCHEDULE" > my_schedule.py
          
          # Check file sizes
          echo "File sizes:"
          ls -la credentials.json calendar_config.json my_schedule.py
          
          # Show first few characters (safe for debugging)
          echo "First 50 chars of credentials.json:"
          head -c 50 credentials.json
          echo -e "\n"
      
      - name: Run calendar update
        run: |
          # Just run a dry-run to test
          python push_schedule.py --dry-run || echo "Failed with code $?"