name: Calendar Sync

on:
  repository_dispatch:
    types: [calendar-sync]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create config & schedule
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          CALENDAR_CONFIG:   ${{ secrets.CALENDAR_CONFIG }}
          MY_SCHEDULE:       ${{ secrets.MY_SCHEDULE }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > service-account-key.json
          echo "$CALENDAR_CONFIG"  > config.json
          echo "$MY_SCHEDULE"      > my_schedule.py

          cat > create_token.py << 'EOF'
          import pickle, json
          from google.oauth2 import service_account

          with open('service-account-key.json') as f:
              info = json.load(f)
          creds = service_account.Credentials.from_service_account_info(
              info, scopes=['https://www.googleapis.com/auth/calendar']
          )
          with open('token.pickle','wb') as t:
              pickle.dump(creds, t)
          EOF
          python create_token.py

      - name: Show loaded schedule
        run: |
          python -c "from my_schedule import schedule; print('Schedule loaded in CI:', schedule)"

      - name: Dry-run push for new events
        run: |
          python push_schedule.py --dry-run

      - name: Push new schedule to Google Calendar
        run: |
          python push_schedule.py
